### **➡️ Broadcasting in NumPy**
- Broadcasting in **NumPy** refers to the ability of arrays with different shapes to be used together in arithmetic operations.  
- It allows NumPy to **"stretch" or "replicate"** smaller arrays across larger ones so that element-wise operations can be performed efficiently — without explicitly copying data.

**📘 Example:** Say you have an array of heights (in meters) & to convert them to cm by multiplying each element by 100.

In [1]:
import numpy as np

heights_m = np.array([1.6, 1.75, 1.8, 1.65])
heights_cm = heights_m * 100

print(heights_cm) # Output: [160. 175. 180. 165.]

[160. 175. 180. 165.]


In [3]:
import numpy as np

heights_m = np.array([1.75, 1.80, 1.65])
heights_correction = np.array([-0.25])

corrected_heights_m = heights_m + heights_correction
print(corrected_heights_m)

[1.5  1.55 1.4 ]


#### **➡️ Broadcasting Arrays of Different Sizes**
- Broadcasting in **NumPy** allows arithmetic operations between arrays of different shapes by **expanding** the smaller array along dimensions where it has size `1`.
- Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding them to compatible dimensions — making array arithmetic both concise and efficient.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])       # Shape: (3,) --> array1 has shape (3,) — a single row with 3 columns.
array2 = np.array([[1], [2], [3]]) # Shape: (3, 1) --> array2 has shape (3, 1) — 3 rows and 1 column.

"""When broadcasting occurs:
1. NumPy stretches array1 vertically to match the number of rows in array2.
2. It stretches array2 horizontally to match the number of columns in array1.
        - After broadcasting, both arrays effectively have the shape (3, 3)
"""

print(array1 + array2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


**🔹Summary**
| Array            | Original Shape | Broadcasted Shape | Description                          |
| ---------------- | -------------- | ----------------- | ------------------------------------ |
| `sales`          | (3, 1)         | (3, 3)            | Expanded horizontally across columns |
| `growth_factors` | (3,)           | (3, 3)            | Expanded vertically across rows      |

When performing operations, NumPy automatically expands the smaller array along the necessary dimensions to match the shape of the larger array.

In [ ]:
import numpy as np

growth_factors = np.array([1.1, 1.2, 1.3]) # Monthly growth factors for 3 months --> # Shape: (3,) [1D Array]
sales = np.array([[10], [20], [30]]) # Monthly sales figures (in thousands) for 3 companies --> # Shape: (3, 1) [2D Array]

forecasted_sales = sales * growth_factors # Applying growth factors to each month's sales

print(forecasted_sales)

[[11. 12. 13.]
 [22. 24. 26.]
 [33. 36. 39.]]


#### **➡️ Broadcasting Rules**
NumPy follows specific rules to determine how arrays with different shapes are **broadcast** together for element-wise operations.

---
##### **📘 Broadcasting Rules Explained**

| **Rule** | **Description** | **Example** 
|-----------|-----------------|--------------
| **Rule 1:** | If the arrays do not have the same number of dimensions (**rank**), prepend the shape of the smaller array with **ones (1s)** until both shapes have the same length. | Shape (3,) → becomes (1, 3) when compared with shape (3, 3). 
| **Rule 2:** | The size of the output in each dimension is the **maximum** of the sizes in that dimension among the input arrays. | Shapes (3, 1) and (1, 4) → output shape (3, 4). |
| **Rule 3:** | Two dimensions are **compatible** for broadcasting if they are equal **or** one of them is **1**. | (3, 1) and (3, 4) → broadcastable ✅; (2, 3) and (3, 2) → not broadcastable ❌ |

In [7]:
import numpy as np

A = np.array([[1], [2], [3]])   # Shape (3, 1)
B = np.array([10, 20, 30])      # Shape (3,)
C = A + B
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


**➡️ `Example`: Given a 3D array representing the temperatures in different cities over several days, convert these temperatures from Celsius to Fahrenheit.**
- **`Fahrenheit = Celsius * 9/5 + 32`**

In [8]:
import numpy as np

temps_celsius = np.array([[[23, 25, 27], [30, 32, 34]],
                          [[21, 23, 25], [28, 30, 32]]])

fahrenheit = (temps_celsius * 9/5) + 32
print(fahrenheit)

[[[73.4 77.  80.6]
  [86.  89.6 93.2]]

 [[69.8 73.4 77. ]
  [82.4 86.  89.6]]]


In [10]:
import numpy as np

matrix = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

vector = np.array([10, 20, 30])

result = matrix + vector

print("Original Matrix:")
print(matrix)
print("\nResulting Matrix after Broadcasting:")
print(result)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Resulting Matrix after Broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
