#### **➡️ Matrix Operations in NumPy**
Matrix operations are essential in various fields such as **image processing**, **machine learning**, **physics simulations**, and **data transformations**.  
`For example`, in image processing, applying transformations like **blurring** or **contrast enhancement** requires performing mathematical operations on pixel matrices.

---
**📘 Key Matrix Operations**

| **Operation** | **Description** | **NumPy Function / Operator** | **Example** |
|----------------|-----------------|-------------------------------|--------------|
| **Matrix Addition** | Adds two matrices element-wise (same shape required). | `+` or `np.add()` | `A + B` |
| **Matrix Subtraction** | Subtracts one matrix from another element-wise. | `-` or `np.subtract()` | `A - B` |
| **Multiplication (Dot Product)** | Performs matrix multiplication (not element-wise). | `np.dot()` or `@` | `A @ B` |
| **Element-wise Multiplication** | Multiplies matrices element-by-element. | `*` or `np.multiply()` | `A * B` |
| **Matrix Transposition** | Flips matrix rows and columns. | `np.transpose(A)` or `A.T` | — |
| **Matrix Inversion** | Finds the inverse of a square matrix. | `np.linalg.inv(A)` | — |
| **Determinant** | Calculates the determinant of a square matrix. | `np.linalg.det(A)` | — |
| **Eigenvalues & Eigenvectors** | Finds eigenvalues and eigenvectors. | `np.linalg.eig(A)` | — |
| **Solving Linear Equations** | Solves system of linear equations `Ax = b`. | `np.linalg.solve(A, b)` | — |


##### **➕ Matrix Addition and Subtraction**
Matrix addition and subtraction are **element-wise operations**, meaning that corresponding elements of two matrices are added or subtracted.  
👉 Both matrices **must have the same shape** for these operations.

In [1]:
import numpy as np

matrix_a = np.array([1, 2, 3])
matrix_b = np.array([9, 8, 7])

print(matrix_a + matrix_b)       # Output: [10 10 10]
print(matrix_a - matrix_b)       # Output: [-8 -6 -4]

[10 10 10]
[-8 -6 -4]


In [3]:
import numpy as np

# Create two 3x3 matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Matrix addition
addition = np.add(matrix_a, matrix_b)
print('Addition: ', addition, '\n')

# Matrix subtraction
substraction = np.subtract(matrix_a, matrix_b)
print('Subtraction: ', substraction)

Addition:  [[10 10 10]
 [10 10 10]
 [10 10 10]] 

Subtraction:  [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


##### **✖️ Matrix Multiplication**
Matrix multiplication involves the **dot product of rows and columns** and is a core operation in **linear algebra**, **machine learning**, and **image processing**.  

Matrix multiplication follows the **compatibility rule**:
> The number of **columns in the first matrix** must equal the number of **rows in the second matrix**.

In [4]:
import numpy as np

matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

result = np.dot(matrix_a, matrix_b)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


**➡️ `Matrix Inversion`:** Matrix inversion finds a matrix that, when multiplied by the original matrix, results in the identity matrix. **Only square matrices (same number of rows and columns) can be inverted.**

In [5]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


➡️ **`Identity Matrix`**: An Identity Matrix is a special square matrix with **ones on its main diagonal** and **zeros elsewhere**.

In [6]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [8]:
# Create two 3x3 matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Matrix multiplication
matrix_mul = np.dot(matrix_a, matrix_b)
print(matrix_mul, '\n')

# Matrix inversion of matrix_c
matrix_c = np.array([[1, 2], [3, 4]])
matrix_inv = np.linalg.inv(matrix_c)
print(matrix_inv, '\n')

# Create an identity matrix
identity_matrix = np.dot(matrix_c, matrix_inv)
print(identity_matrix, '\n')
# since matrix_inv has floating point values, the identity matrix - the result shows very small numerical errors
# To round the result of matrix multiplication and eliminate small numerical errors, you can use the np.round() function
rounded_result = np.round(identity_matrix)
print(rounded_result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]] 

[[1. 0.]
 [0. 1.]]


➡️ **Matrix Transposition**: The **transpose** of a matrix flips it over its diagonal, switching rows and columns.

- `Formula`: **np.transpose(matrix_a) or matrix_a.T**

In [10]:
import numpy as np

matrix_a = np.array([[1], [2], [3]])
print("Original Matrix:")
print(matrix_a)

print("\nTransposed Matrix:")
print(np.transpose(matrix_a)) # or print(matrix_a.T)

Original Matrix:
[[1]
 [2]
 [3]]

Transposed Matrix:
[[1 2 3]]


In [12]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix:")
print(matrix_a)

print("Transpose of the Matrix:")
print(matrix_a.T)

Original Matrix:
[[1 2 3]
 [4 5 6]]
Transpose of the Matrix:
[[1 4]
 [2 5]
 [3 6]]


##### **➡️ Question The system of linear equations can be written in the form A⋅X = B, where:**
``` python
🔹 A [Coefficient matrix A] = [[2, 1, -1] [-3, -1, 2] [-2, 1, 2]]
🔹 X [Variable matrix X] = [[x] [y] [z]]
🔹 B [Constant matrix B] = [[8] [-11] [-3]]
```

- To solve for X, we use the equation **`X = A^−1 . B`** where A^−1 is the inverse of matrix A.

In [1]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Constant matrix B
B = np.array([[8],
              [-11],
              [-3]])

# Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Solve for X using the equation X = A_inv * B
X = np.dot(A_inv, B)
print(X)

[[ 2.]
 [ 3.]
 [-1.]]


##### ➡️ **Linear equations - Practice problem**
- x + y + z + w = 10
- 2x + 3y+ 1z + 4w = 28
- 3x + y + 2z + w = 19
- 4x + 2y + 3z + 3w = 35

**Setup the matrices A, B - calculate the inverse of A and then solve for the variables. Output the matrix X to the console.**

In [2]:
import numpy as np

# Coefficient matrix A
A = np.array([[1, 1, 1, 1],
              [2, 3, 1, 4],
              [3, 1, 2, 1],
              [4, 2, 3, 3]])

# Constant matrix B
B = np.array([[10],
              [28],
              [19],
              [35]])

# Calculating the inverse of matrix A
A_inv = np.linalg.inv(A)

# Solving for X using the equation X = A_inv * B
X = np.dot(A_inv, B)
print(X)

[[ 3.33333333]
 [-1.66666667]
 [ 2.33333333]
 [ 6.        ]]
