#### ➡️ **Set Operations in NumPy**
Set operations help you handle unique elements, find common elements, and identify differences between arrays. They are especially useful in:
- Data cleaning
- Identifying duplicates
- Merging datasets
- Machine learning preprocessing
- Database-like operations

➡️ **Unique Elements in NumPy**: The `np.unique()` function returns the sorted unique elements of an array.


**🔹 Example with 1D array:**

In [1]:
import numpy as np

A = np.array([1, 1, 3, 4, 3, 6])
unique_A = np.unique(A)

print(f"Unique elements in A: {unique_A}")

Unique elements in A: [1 3 4 6]


**🔹 Example with 2D array:** 

In a 2D array, `np.unique()` can find unique elements across the entire array. This is useful for analyzing survey responses or datasets from multiple groups.

In [3]:
A = np.array([
    [1, 2, 3],
    [3, 4, 2],
    [1, 5, 3]
])
unique_A = np.unique(A)
print(f"Unique element in 2D array A: {unique_A}")

Unique element in 2D array A: [1 2 3 4 5]


**➡️ In this example:**
- **`survey_responses`** is a 2D array where each row corresponds to responses from a different group.
- We extract responses to a specific question (question 2 in this case) using `slicing (survey_responses[:, 1])`.
- **`np.unique`** function is used to find unique responses to question 2 across all groups.

In [6]:
import numpy as np

# Example 2D array representing survey responses
survey_responses = np.array([
    [1, 2, 3, 4],
    [3, 4, 5, 6],
    [1, 2, 3, 7],
    [2, 3, 4, 5]
])
# Find unique responses across all groups for a particular question (e.g., question 2)
question_responses = survey_responses[:, 1]  # Selecting responses to question 2 (column index 1)
print(question_responses)

unique_responses = np.unique(question_responses)
print("Unique responses to question 2:", unique_responses)

[2 4 2 3]
Unique responses to question 2: [2 3 4]


#### ➡️ **Intersection, Union, and Set Difference in NumPy**
Set operations help in identifying common or unique elements between arrays.

---
##### 🔹 **Summary of Set Operations in NumPy**
| Operation          | Function             | Description                                           | Example Output       |
|-------------------|-------------------|---------------------------------------------------|--------------------|
| Unique Elements    | `np.unique(array)`  | Returns sorted unique elements of an array        | `[1 3 4 6]`        |
| Intersection       | `np.intersect1d(a, b)` | Returns sorted elements common to both arrays    | `[3 4]`            |
| Union              | `np.union1d(a, b)` | Returns sorted unique elements from both arrays   | `[1 2 3 4 5 6]`    |
| Set Difference     | `np.setdiff1d(a, b)` | Returns elements in `a` not in `b`               | `[1 2]`            |


**1️⃣ `Intersection`: Elements common to both arrays.**

In [12]:
import numpy as np

campaign_a = np.array([1, 2, 3, 4, 5, 6])
campaign_b = np.array([4, 5, 6, 7, 8, 9])

print(np.intersect1d(campaign_a, campaign_b))  # Output - [3 4]

[4 5 6]


**2️⃣ `Union`: All unique elements from both arrays.**

In [11]:
campaign_a = np.array([1, 2, 3, 4, 5, 6])
campaign_b = np.array([4, 5, 6, 7, 8, 9])

print(np.union1d(campaign_a, campaign_b))      # Output - [1 2 3 4 5 6]

[1 2 3 4 5 6 7 8 9]


**3️⃣ `Set Difference`: Elements in the first array but not in the second.**

In [10]:
campaign_a = np.array([1, 2, 3, 4, 5, 6])
campaign_b = np.array([4, 5, 6, 7, 8, 9])

print(np.setdiff1d(campaign_a, campaign_b))    # Output - [1 2]

[1 2 3]


➡️ **Task: Set Operations on Customer IDs**

You are given 2 1D arrays in the IDE. Compute and output the following to the console:
1. Unique customer IDs in each campaign.  
2. Common customer IDs in both campaigns.  
3. All customer IDs combined.  
4. Customer IDs in `campaign_c` but not in `campaign_d`.

In [13]:
import numpy as np

campaign_c = np.array([10, 11, 12, 13, 14])
campaign_d = np.array([13, 14, 15, 16, 17])

# Unique customer IDs in each campaign
unique_id_c = np.unique(campaign_c)
unique_id_d = np.unique(campaign_d)

print(f"Unique Id in campaign_c: {unique_id_c}")
print(f"Unique Id in campaign_d: {unique_id_d}")

# Common customer IDs in both campaigns
common_id = np.intersect1d(campaign_c, campaign_d)
print("Common Id in both campaigns: ", common_id)

# All customer IDs combined
union_id = np.union1d(campaign_c, campaign_d)
print(f"All Ids combined: {union_id}")

# Customer IDs in campaign_c but not in campaign_d
id_not = np.setdiff1d(campaign_c, campaign_d)
print(f"Customer Id in campaign_c but not in campaign_d: {id_not}")

Unique Id in campaign_c: [10 11 12 13 14]
Unique Id in campaign_d: [13 14 15 16 17]
Common Id in both campaigns:  [13 14]
All Ids combined: [10 11 12 13 14 15 16 17]
Customer Id in campaign_c but not in campaign_d: [10 11 12]
