### **🔹Element-wise Operations in NumPy**
Element-wise operations allow you to perform arithmetic operations on arrays element by element. When two arrays have the same shape, NumPy applies the operation to each corresponding pair of elements.

**➡️ Explanation**
- **`+`** → Adds elements pairwise.
- **`-`** → Subtracts elements pairwise.
- **`*`** → Multiplies elements pairwise.
- **`/`** → Divides elements pairwise, returns floats.
- **`%`** → Computes the remainder of element-wise division.
---
**🔹 Note:**
1. All arithmetic operations are **vectorized**, meaning they are performed much faster than using loops over Python lists.
2. Arrays must have the same shape unless broadcasting rules apply.

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Output: [5 7 9]
print(a - b)   # Output: [-3 -3 -3]
print(a * b)   # Output: [ 4 10 18]
print(a / b)   # Output: [0.25 0.4 0.5]
print(b % a)   # Output: [0 1 0]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 1 0]


### **➡️ Scalar Operations in NumPy**
- Scalar operations involve performing arithmetic operations between a NumPy array and a single scalar value. The scalar is applied to each element of the array.
- Scalar operations are element-wise and are vectorized, making them faster than looping over arrays manually.

In [2]:
import numpy as np

a = np.array([1, 2, 3])

result = a + 10 # + → Adds the scalar to each element.
print(result)   # Output: [11 12 13]

result = a - 10 # - → Subtracts the scalar from each element.
print(result)   # Output: [-9 -8 -7]

result = a * 10 # * → Multiplies each element by the scalar.
print(result)   # Output: [10 20 30]

result = a / 10 # / → Divides each element by the scalar.
print(result)   # Output: [0.1 0.2 0.3]

[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]


### **➡️ Built-in Functions for Arithmetic Computations in NumPy**
- NumPy provides built-in functions to perform various arithmetic computations on arrays, such as sum, product, cumulative sum, and cumulative product.
- `cumsum` and `cumprod` are useful for running totals and progressive multiplications, often used in statistics, finance, and scientific computations.

**➡️ Explanation**
- `np.sum(a)` → Returns the sum of all elements in the array.
- `np.prod(a)` → Returns the product of all elements in the array.
- `np.cumsum(a)` → Computes the cumulative sum: each element is the sum of itself and all previous elements.
- `np.cumprod(a)` → Computes the cumulative product: each element is the product of itself and all previous elements.

In [6]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])

print(np.sum(a))       # Output: 35
print(np.prod(a))      # Output: 86400
print(np.cumsum(a))    # Output: [ 1  3  6 10 15 17 20 24 29 35]
print(np.cumprod(a))   # Output: [1     2     6    24   120   240   720  2880 14400 86400]

35
86400
[ 1  3  6 10 15 17 20 24 29 35]
[    1     2     6    24   120   240   720  2880 14400 86400]


### **➡️ Built-in Functions for Arithmetic Computations**
- `np.add(a, b)` → Adds corresponding elements.
- `np.subtract(a, b)` → Subtracts elements of b from a.
- `np.multiply(a, b)` → Multiplies corresponding elements.
- `np.divide(a, b)` → Divides elements of a by b (element-wise).

In [7]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Element-wise addition
sum_array = np.add(a, b)
print("Element-wise addition:", sum_array)

# Element-wise subtraction
diff_array = np.subtract(a, b)
print("Element-wise subtraction:", diff_array)

# Element-wise multiplication
prod_array = np.multiply(a, b)
print("Element-wise multiplication:", prod_array)

# Element-wise division
div_array = np.divide(a, b)
print("Element-wise division:", div_array)

Element-wise addition: [6 6 6 6 6]
Element-wise subtraction: [-4 -2  0  2  4]
Element-wise multiplication: [5 8 9 8 5]
Element-wise division: [0.2 0.5 1.  2.  5. ]
