### ➡️ Comparison Operations in NumPy
- Comparison operations in NumPy are used to compare elements of arrays element-wise.
- **These comparisons use operators such as:**
1. `>` — Greater than
2. `<` — Less than
3. `>=` — Greater than or equal to
4. `<=` — Less than or equal to
5. `==` — Equal to
6. `!=` — Not equal to
---
**➡️ Note: Each comparison returns a boolean array, where each element represents whether the comparison is `True or False`.**

In [1]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

print(array1 > array2)    # Output: [False False False  True  True]
print(array1 < array2)    # Output: [ True  True False False False]
print(array1 == array2)   # Output: [False False  True False False]

[False False False  True  True]
[ True  True False False False]
[False False  True False False]


In [2]:
import numpy as np

arr1 = np.array([[ 1,  2,  3], [ 4,  5,  6]])
arr2 = np.array([[ 4,  5,  6], [ 1,  2,  3]])

# Update your code below this line
print(arr1 >= arr2)
print(arr1 != arr2)

[[False False False]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]]


### **➡️ Logical Computations in NumPy**
Logical computations in NumPy are used to perform element-wise logical operations on boolean arrays.
They help combine or invert boolean conditions efficiently.

---
**➡️ Common logical functions include:**
- **`np.logical_and()`** → Returns `True` if both conditions are `True`.
- **`np.logical_or()`** → Returns `True` if at least one condition is `True`.
- **`np.logical_not()`** → Inverts the boolean values (`True` → `False`, `False` → `True`).
- **`np.logical_xor()`** → Returns `True` if only one of the conditions is `True`.

In [4]:
import numpy as np

# Create two boolean arrays
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

# Perform logical AND operation
result = np.logical_and(a, b)
print("Logical AND:", result)

# Perform logical OR operation
result = np.logical_or(a, b)
print("Logical OR:", result)

# Perform logical NOT operation
result = np.logical_not(a)
print("Logical NOT:", result)

# Perform logical XOR operation
result = np.logical_xor(a, b)
print("Logical XOR:", result)

Logical AND: [ True False False False]
Logical OR: [ True  True  True False]
Logical NOT: [False  True False  True]
Logical XOR: [False  True  True False]


### **➡️ Combining Logical Computations in NumPy**
- NumPy allows you to combine **multiple logical operations** using parentheses `()` for grouping, enabling the creation of complex logical expressions.
- This helps in filtering or decision-making based on multiple conditions simultaneously.

In [7]:
import numpy as np

# Creating two 2D boolean arrays
array1 = np.array([[True, False, True], [False, True, False]])
array2 = np.array([[False, True, True], [True, False, True]])

# Element-wise logical AND
logical_and_result = np.logical_and(array1, array2)

# Element-wise logical NOT
logical_not_result = np.logical_not(array1)

# Combining logical operations: (array1 AND array2) OR NOT array1
combined_result = np.logical_or(logical_and_result, logical_not_result)

# Print the results
print("Array1:\n", array1, "\n")
print("Array2:\n", array2, "\n")
print("Logical AND Result:\n", logical_and_result, "\n")
print("Logical NOT Result:\n", logical_not_result, "\n")
print("Combined Logical Operation Result:\n", combined_result)

Array1:
 [[ True False  True]
 [False  True False]] 

Array2:
 [[False  True  True]
 [ True False  True]] 

Logical AND Result:
 [[False False  True]
 [False False False]] 

Logical NOT Result:
 [[False  True False]
 [ True False  True]] 

Combined Logical Operation Result:
 [[False  True  True]
 [ True False  True]]


In [8]:
import numpy as np

def filter_matrix_elements(matrix, threshold):
    # Element-wise comparison to check if elements are greater than the threshold
    greater_than_comparision = matrix > threshold

    # Element-wise comparison to check if elements are even
    even_element = (matrix % 2 == 0)

    # Combining the two conditions using logical AND
    criteria = np.logical_and(greater_than_comparision, even_element)

    # Creating the result array where elements meeting criteria are retained, others are set to 0
    result = matrix * criteria

    return result

matrix = np.array([
    [1, 12, 15],
    [8, 23, 4],
    [9, 6, 17]
])
threshold = 10

filtered_matrix = filter_matrix_elements(matrix, threshold)
print(filtered_matrix)

[[ 0 12  0]
 [ 0  0  0]
 [ 0  0  0]]
