In [1]:
# ------------------------------------------------ Numpy Array Indexing & Slicing -----------------------------------------------
## Contents:--
    #-- How to identify the datatypes, size and bytes of elements in arrays
    #-- Indexing in arrays to refer to specific elements similar to lists
    #-- Slicing in arrays to extract and modify specific elements

### **Basic Array Attributes in NumPy**
NumPy arrays come with several built-in attributes that provide essential information about their structure and memory usage.  
These attributes help in understanding how data is stored and handled efficiently.

---
**➡️ Summary:**
| Attribute       | Description                            | Example Output                      |
| --------------- | -------------------------------------- | ----------------------------------- |
| **`.size`**     | Number of elements in the array        | `3`                                 |
| **`.dtype`**    | Data type of array elements            | `int64`                             |
| **`.itemsize`** | Memory size (in bytes) of each element | `2`, `4`, or `8` depending on dtype |

##### **1. `.size` — Number of Elements**: Returns the **total number of elements** in the NumPy array -> `.size` counts all elements, even in multi-dimensional arrays.

In [6]:
# Example of 1D array:
import numpy as np

num = np.array([1, 2, 3])
print("1D Array:", num.size)   # Output: 3

# Example of 2D array:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("2D Array:", arr.size)   # Output: 6

1D Array: 3
2D Array: 6


##### **🔹 2. `.dtype` — Data Type of Elements**: Returns the data type of the array’s elements.

In [7]:
num = np.array([1, 2, 3])
print(num.dtype)   # Output: int64

int64


##### **3. `.itemsize` — Memory Size of Each Element**: Returns the size (in bytes) of each element in the array.

In [9]:
"""
Each element takes 2 bytes because int16 uses 16 bits (2 bytes).
int32 would use 4 bytes per element, and float64 uses 8 bytes.
"""
num = np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(num.itemsize)  # Output: 2

2


In [10]:
num = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(num.itemsize)  # Output: 8

8


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) # Create an array of integers

print("Size of the array:", arr.size) # .size --> Print the number of elements in the array
print("Data type of the array elements:", arr.dtype) # .dtype --> Print the data type of the array elements
print("Item size of the array elements:", arr.itemsize) # .itemsize --> Print the size in bytes of each element in the array

Size of the array: 5
Data type of the array elements: int64
Item size of the array elements: 8


### **Array Indexing in NumPy**
Array indexing in NumPy allows you to **access and modify specific elements** within an array.  
It works similarly to Python lists but is much faster and supports advanced multidimensional operations.

---
**➡️ Summary**
| Operation    | Description                 | Example        | Output              |
| ------------ | --------------------------- | -------------- | ------------------- |
| `arr[i]`     | Access element at index `i` | `arr[2]`       | `30`                |
| `arr[-i]`    | Access element from the end | `arr[-3]`      | `30`                |
| `arr[i] = x` | Modify element at index `i` | `arr[2] = 100` | `[10 20 100 40 50]` |

**1. Accessing Elements (0-Based Indexing)**: NumPy arrays use **0-based indexing**, meaning the first element has index `0`.

In [1]:
import numpy as np

arr_1d = np.array([10, 20, 30, 40, 50])
print(arr_1d[2])   # Output: 30

30


**2. Negative Indexing:** Negative indices allow you to access elements from the **end** of the array.

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-3])   # Output: 30

30


**3. Modifying Elements via Indexing:** You can update elements in an array directly using indexing.

In [3]:
arr = np.array([10, 20, 30, 40, 50])
arr[2] = 100
print(arr)    # Output: [ 10  20 100  40  50]

[ 10  20 100  40  50]


In [6]:
import numpy as np

arr_1d = np.array([10, 20, 30, 40, 50])
print(arr_1d[3])

n = 2
print(arr_1d[n])

arr_1d[-1] = 100 # Updating Array using Negative Indexing
print(arr_1d)

40
30
[ 10  20  30  40 100]


### **Array Slicing in NumPy**
Array slicing in NumPy is a **powerful and efficient way to extract subsets** of data from arrays without creating copies (in most cases).  

---
##### ➡️ **General Syntax:** `array[start:stop:step]`
| Parameter | Description                                | Default      |
| --------- | ------------------------------------------ | ------------ |
| `start`   | Index where slicing **starts** (inclusive) | `0`          |
| `stop`    | Index where slicing **ends** (exclusive)   | End of array |
| `step`    | Difference between each index (increment)  | `1`          |

1️⃣ **Basic Slicing Example**

In [9]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])   # Output: [2 3 4 5] -> Starts at index 2, ends before index 6

[2 3 4 5]


**2️⃣ Omitting Start or Stop**

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[:5])   # Output: [0 1 2 3 4] -> arr[:5] → From the beginning to index 5 (exclusive)
print(arr[5:])   # Output: [5 6 7 8 9] -> arr[5:] → From index 5 (inclusive) to the end

[0 1 2 3 4]
[5 6 7 8 9]


**3️⃣ Using Negative Indices**

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[-4:])   # Output: [6 7 8 9] -> arr[-4:] → Last 4 elements
print(arr[:-4])   # Output: [0 1 2 3 4 5] -> arr[:-4] → All elements except the last 4

[6 7 8 9]
[0 1 2 3 4 5]


**4️⃣ Using Step Values**

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[::2])      # Output: [0 2 4 6 8] -> arr[::2] → Every second element of the entire array
print(arr[7:1:-2])   # Output: [7 5 3] -> arr[7:1:-2] → From index 7 down to index 2, stepping backward by 2

[0 2 4 6 8]
[7 5 3]


In [19]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:6:3])
print(arr[-2:-6:-1])
print(arr[7:0:-2])

[2 5]
[8 7 6 5]
[7 5 3 1]


### **Boolean Indexing in NumPy**
**Boolean indexing** in NumPy allows you to **filter elements** of an array based on conditions rather than index positions.  
It’s a powerful and efficient way to extract elements that **meet specific criteria**.

---
**➡️ `Concept`**: When you apply a **conditional expression** to a NumPy array, it returns a **Boolean array** (`True`/`False`) of the same shape — where each value indicates whether the condition is satisfied.

**1️⃣ Basic Example**

In [20]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
condition = arr > 25 # NumPy checks each element — if it’s greater than 25, the result is True, otherwise False.
print(condition)

[False False  True  True  True]


**2️⃣ Filtering Elements Using Boolean Indexing**

In [21]:
filtered = arr[arr > 25] # The Boolean array acts as a mask — only the elements corresponding to True values are selected.
print(filtered)

[30 40 50]


**3️⃣ Combining Multiple Conditions using Bitwise operators**
- **`&`** → Logical **AND**
- **`|`** → Logical **OR**
- **`~`** → Logical **NOT**

In [22]:
arr = np.array([5, 15, 25, 35, 45])
filtered = arr[(arr > 10) & (arr < 40)]

print(filtered)

[15 25 35]


**4️⃣ Using Boolean Indexing to Modify Values**

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr % 2 == 0] = 0 # All even numbers (where the condition arr % 2 == 0 is True) are replaced with 0.

print(arr)

[1 0 3 0 5]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # Sample array
print("Original array:", arr)

mask = arr > 5 # Boolean mask
print("Boolean mask:  ", mask)

filtered_arr = arr[mask] # Use the boolean mask to index the array
print("Filtered array:", filtered_arr)

# You can also create and apply a mask in one step
even_numbers = arr[arr % 2 == 0]
print("Even numbers: ", even_numbers)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Boolean mask:   [False False False False False  True  True  True  True  True]
Filtered array: [ 6  7  8  9 10]
Even numbers:  [ 2  4  6  8 10]


**➡️ Example: Selecting Even Numbers Greater Than 50**

In [27]:
"""
The condition (data % 2 == 0) checks for even numbers.
The condition (data > 50) checks for values greater than 50.
Combining them with & selects numbers that satisfy both conditions.
"""
import numpy as np

data = np.array([15, 22, 13, 48, 55, 62, 73, 84, 91, 102])

mask = (data % 2 == 0) & (data > 50)
print(data[mask])

[ 62  84 102]


**2️⃣ Modifying Elements Using Boolean Indexing:** You can also use Boolean indexing to modify specific elements of an array directly.

**➡️ Example: Replace Values Greater Than 20 with -1**

In [28]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
arr[arr > 20] = -1 # Every element satisfying the condition (arr > 20) is replaced with -1.

print(arr)

[ 5 10 15 20 -1 -1 -1 -1]


In [30]:
# Debug the code given below

import numpy as np

# Create an array of integers
arr = np.array([5, 12, 17, 24, 29, 33, 41, 56])

# Create a boolean mask for elements greater than 20
mask = arr > 20

# Use the mask to filter the array
filtered_arr = arr[mask]
print("Filtered array:", filtered_arr)

# Use the mask to set elements greater than 20 to -1
arr[mask == True] = -1
print("Modified array:", arr)

# Create a new mask for even elements
even_mask = arr % 2 == 0

# Use the mask to filter the array
even_filtered_arr = arr[even_mask]
print("Even filtered array:", even_filtered_arr)


Filtered array: [24 29 33 41 56]
Modified array: [ 5 12 17 -1 -1 -1 -1 -1]
Even filtered array: [12]


### **➡️ Integer Array Indexing in NumPy**
NumPy allows you to use **arrays of integers** as indices to extract specific elements from another array.  
This is known as **integer array indexing**, and it provides a flexible way to access multiple non-contiguous elements at once.

**🔹 Example: Extracting Specific Elements**

In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 4])

print(arr[indices]) # arr[indices] fetches the elements from arr at positions 1, 3, and 4.

[20 40 50]


**🔹 Ques 1: Accept 3 integers as input and output the array values corresponding to these indices.**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index_list = list(map(int, input().split()))

print(arr[index_list])

[20 30 40]
