### ➡️ **Introduction to Numpy**

##### **Why Use NumPy**
NumPy (Numerical Python) is one of the most powerful libraries in Python for **numerical computing, data manipulation, and mathematical operations**.  
It’s built for **speed, efficiency, and flexibility**, making it essential for data science, machine learning, and scientific computing.

---
#### **What Makes NumPy Powerful**
##### ➡️ **Performance and Efficiency**
1. **Faster Computations**  
- NumPy arrays (known as **ndarrays**) are implemented in **C**, not pure Python.  
- They use **contiguous memory blocks**, allowing efficient looping at the hardware level.  
- As a result, operations on NumPy arrays are **much faster** than equivalent operations on Python lists.
2. **Memory Efficiency**
- Python lists store elements as individual Python objects, each with metadata (type, reference count, etc.).
- NumPy arrays store elements of the same data type in a compact, fixed-size block, reducing memory overhead.

In [2]:
import random
import time
import numpy as np

# Method 1: Using Lists: Generate a large list of random numbers
data_list = [random.random() for _ in range(1000000)]

# Calculate the mean using Python lists
start = time.time()
mean_list = sum(data_list) / len(data_list)
end = time.time()

print("Mean (list):", mean_list)
print("Time taken (list):", end - start, "\n")

# Method 2: Using NumPy: Generate a large NumPy array of random numbers
data_array = np.random.random(1000000)

# Calculate the mean using NumPy
start = time.time()
mean_array = np.mean(data_array)
end = time.time()
print("Mean (NumPy):", mean_array)
print("Time taken (NumPy):", end - start)

Mean (list): 0.5001996061288194
Time taken (list): 0.006627798080444336 

Mean (NumPy): 0.5003883974641029
Time taken (NumPy): 0.002344369888305664


### **Why Use NumPy (Continued)**
NumPy’s popularity is its **rich collection of mathematical and statistical functions**. These functions are optimized in C, making computations not only simpler but also significantly faster compared to manual looping in Python.

---
#### **2. Mathematical Functions**
- **Trigonometric functions:** `np.sin()`, `np.cos()`, `np.tan()`
- **Logarithmic functions:** `np.log()`, `np.log10()`
- **Exponential functions:** `np.exp()`
- **Rounding functions:** `np.round()`, `np.floor()`, `np.ceil()`
---
#### **3. Statistical Functions**
- **Mean**: np.mean()
- **Median**: np.median()
- **Standard deviation**: np.std()
- **Variance**: np.var()
- **Min/Max**: np.min(), np.max(), np.percentile()
---
NumPy eliminates the need for manual loops in mathematical and statistical operations by offering optimized, ready-to-use, vectorized functions — making complex calculations concise and lightning-fast.

In [3]:
import math
import random
import numpy as np

# Method 1: Using regular Python: Generate a large list of random numbers
data_list = [random.random() for _ in range(1000)]

# Calculate the mean and standard deviation
mean_list = sum(data_list) / len(data_list)
variance_list = sum((x - mean_list) ** 2 for x in data_list) / len(data_list)
std_dev_list = math.sqrt(variance_list)

print("Mean (list):", mean_list)
print("Standard Deviation (list):", std_dev_list, '\n')

# Method 2: Using NumPy: Generate a large NumPy array of random numbers
data_array = np.random.random(1000)

# Calculate the mean
mean_array = np.mean(data_array)
std_dev_array = np.std(data_array)

print("Mean (NumPy):", mean_array)
print("Standard Deviation (NumPy):", std_dev_array)

Mean (list): 0.494061693587044
Standard Deviation (list): 0.28827554596119076 

Mean (NumPy): 0.51212874353881
Standard Deviation (NumPy): 0.294519315692774


### **3. Array Manipulation and Operations**
NumPy provides a powerful set of features to **reshape, combine, and perform operations on arrays** efficiently.  
These capabilities make it ideal for numerical, scientific, and data analysis tasks.

---
##### **✅ Reshaping Arrays**
You can change the **shape or dimensionality** of an array without altering its data using functions like `reshape()`, `flatten()`, and `transpose()`.

---
##### ✅ **Broadcasting**
Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding dimensions where possible.
This avoids explicit looping and ensures operations remain vectorized and fast.

---
##### ➡️ **Summary**
| Feature          | Description                                       | Example             |
| ---------------- | ------------------------------------------------- | ------------------- |
| **Reshape**      | Changes array dimensions without altering data    | `arr.reshape(3, 2)` |
| **Flatten**      | Converts multidimensional arrays to 1D            | `arr.flatten()`     |
| **Transpose**    | Swaps rows and columns                            | `arr.T`             |
| **Broadcasting** | Allows arithmetic on arrays with different shapes | `a + b`             |

In [2]:
import numpy as np

# Method 1: Using Python Lists: Create a 1D list
data_list = [1, 2, 3, 4, 5, 6]

# Reshape into a 2x3 "matrix"
data_matrix = [data_list[i:i + 3] for i in range(0, len(data_list), 3)]
print("Reshaped list (2x3):")
print(data_matrix)

# Transpose the "matrix"
transposed_matrix = [[data_matrix[j][i] for j in range(len(data_matrix))] for i in range(len(data_matrix[0]))]
print("Transposed list (3x2):")
print(transposed_matrix, '\n')

# Method 2: Using NumPy: Create a 1D NumPy array
data_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape into a 2x3 matrix
reshaped_array = data_array.reshape((2, 3))
print("Reshaped array (2x3):")
print(reshaped_array)

# Transpose the matrix
transposed_array = reshaped_array.T
print("Transposed array (3x2):")
print(transposed_array)

Reshaped list (2x3):
[[1, 2, 3], [4, 5, 6]]
Transposed list (3x2):
[[1, 4], [2, 5], [3, 6]] 

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
Transposed array (3x2):
[[1 4]
 [2 5]
 [3 6]]
