##### ➡️ **Numpy Array Creation**

In [3]:
import numpy as np

data_array = np.array([1, 2, 3, 4, 5, 6]) # Create a 1D NumPy array

print(data_array)

[1 2 3 4 5 6]


### **Creating NumPy Arrays Using `randint()`**
NumPy provides tools to generate arrays filled with **random integers**, making it useful for testing, simulations, and statistical experiments.

---
#### **🔹 Using `np.random.randint()`**
The `np.random.randint()` function generates random integers within a specified range and returns them as a NumPy array.

##### ➡️ Syntax: **np.random.randint(low, high, size)**
| Parameter | Description                                                       |
| --------- | ----------------------------------------------------------------- |
| **low**   | The lowest (inclusive) integer that can be generated.             |
| **high**  | The highest (exclusive) integer that can be generated.            |
| **size**  | The shape of the output array (number of elements or dimensions). |

##### **Example: 1D Random Integer Array**

In [4]:
import numpy as np

# Generate an array of 5 random numbers
array1 = np.random.rand(5)
print(array1)

# Generate an array of 5 Random integers between 0 and 10
random_array = np.random.randint(0, 10, size=5)
print(random_array)

[0.69384405 0.68340536 0.21977563 0.95254487 0.20389132]
[2 9 0 1 4]


##### **Example: 2D Random Integer Array**

In [5]:
# Create a 2D array (3x4) of random integers between 10 and 50
matrix = np.random.randint(10, 50, size=(3, 4))

print(matrix)

[[22 38 35 42]
 [45 34 35 44]
 [28 43 45 21]]


### **Creating Empty, Zero, and One Arrays in NumPy**
NumPy provides built-in functions to quickly create arrays that are either **empty**, filled with **zeros**, or filled with **ones**.  
These functions are particularly useful for initializing arrays before assigning or computing values.

---
➡️ **Summary**
| Function      | Description                        | Example       | Output          |
| ------------- | ---------------------------------- | ------------- | --------------- |
| `np.empty(n)` | Creates an uninitialized array     | `np.empty(5)` | Random values   |
| `np.zeros(n)` | Creates an array filled with zeros | `np.zeros(4)` | `[0. 0. 0. 0.]` |
| `np.ones(n)`  | Creates an array filled with ones  | `np.ones(3)`  | `[1. 1. 1.]`    |
---
➡️ **Key Takeaways**
1. Use `empty()` when performance is critical and values will be assigned later.
2. Use `zeros()` or `ones()` when you need predictable initial values.
3. All three functions support multi-dimensional arrays via the `shape` parameter, e.g. `np.zeros((2,3)).`

**🔹 1. Creating an Empty Array — `np.empty()`**
- `np.empty(5)` creates an array of length 5, but does not initialize the values.
- The contents are whatever happens to be in memory — meaning the values are unpredictable `(garbage values)`.
- Use this when you plan to assign all values later, for maximum speed.

In [6]:
import numpy as np

num = np.empty(5)
print(num)

[0.69384405 0.68340536 0.21977563 0.95254487 0.20389132]


**🔹 2. Creating an Array of Zeros — `np.zeros()`**
- Creates an array of length 4, with all elements initialized to 0.
- Default data type is `float64`, but you can specify another using `dtype`, e.g. `np.zeros(4, dtype=int)`.

In [8]:
num0 = np.zeros(4)
print(num0)

[0. 0. 0. 0.]


**🔹 3. Creating an Array of Ones — `np.ones()`**

In [9]:
num1 = np.ones(3)
print(num1)

[1. 1. 1.]


In [10]:
import numpy as np

num0 = np.zeros(4) # create an array with 4 elements filled with zeros
num1 = np.ones(4) # create an array with 3 elements filled with ones
num = np.empty(4) # create an empty array of length 5

print(num0)
print(num1)
print(num)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2.12199579e-314 4.67296746e-307 5.17780797e-321 9.97338022e-312]


#### **Creating Arrays Using `np.arange()`**
The `np.arange()` function in NumPy is used to generate arrays with evenly spaced values within a specified range.  
It works similarly to Python’s built-in `range()` but **returns a NumPy array** instead of a list, allowing for efficient numerical operations.

---
**🔹 Syntax**: `numpy.arange(start, stop, step, dtype=None)`
| Parameter              | Description                                          |
| ---------------------- | ---------------------------------------------------- |
| **start** *(optional)* | Starting value of the sequence. Default is `0`.      |
| **stop**               | End value of the sequence *(excluded)*.              |
| **step** *(optional)*  | Interval between consecutive values. Default is `1`. |
| **dtype** *(optional)* | Specifies the data type of the output array.         |
---
**🔹 Key Takeaways**
1. `np.arange()` is efficient for generating regularly spaced numeric sequences.
2. The **stop value** is always **excluded**.
3. Works seamlessly with integer and **float** steps.
4. For non-integer step values, prefer `np.linspace()` to avoid floating-point precision issues.

**🔹 Example 1 — Basic Usage**

In [11]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**🔹 Example 2 — Custom Start, Stop, and Step**

In [12]:
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


**🔹 Example 3 — Creating Float Arrays**

In [13]:
arr = np.arange(0, 6, dtype=float)
print(arr)

[0. 1. 2. 3. 4. 5.]


In [16]:
# Numpy array with all the even numbers starting from 2 and ending at 10. Their datatype needs to be float.

arr = np.arange(2, 11, 2, dtype=float)
print(arr)

[ 2.  4.  6.  8. 10.]
