#### **N-Dimensional Arrays in NumPy**

##### **Overview**
N-dimensional arrays, or **ndarrays**, are the **core data structure** in NumPy.  
They allow efficient storage and manipulation of **multi-dimensional data**, making NumPy a fundamental tool for **scientific computing**, **data analysis**, and **machine learning**.

---
➡️ **Why N-Dimensional Arrays Matter**: NumPy arrays go beyond simple lists — they can represent complex data structures such as:
- **`1D arrays`** → vectors or sequences  
- **`2D arrays`** → matrices or tables  
- **`3D arrays`** → images, videos, or volumetric data  
- **`nD arrays`** → higher-dimensional scientific or simulation data  
These arrays allow for efficient **vectorized operations**, **broadcasting**, and **fast computations** compared to Python lists.

---
**➡️ In Practice:**
- **`1D arrays`** → time-series data
- **`2D arrays`** → Excel sheets or grayscale images
- **`3D arrays`** → color images or stacked matrices
- **`4D+ arrays`** → video frames, deep learning tensors

**➡️ Example: Creating Multi-Dimensional Arrays**

In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3D array (tensor-like)
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Shapes of Arrays
print(arr_1d.ndim)   # Output: 1 -> .ndim helps you understand **number of dimensions (axes)** of an array
print(arr_2d.ndim)   # Output: 2
print(arr_3d.ndim)   # Output: 3

print(arr_2d.shape)  # Output: (2, 3)

1
2
3
(2, 3)


In [2]:
import numpy as np

# Creating a 3x3 RGB image
image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],  # Row 1: Red, Green, Blue
    [[255, 255, 0], [0, 255, 255], [255, 0, 255]],  # Row 2: Yellow, Cyan, Magenta
    [[192, 192, 192], [128, 128, 128], [0, 0, 0]]  # Row 3: Light Gray, Gray, Black
])

print("3x3 RGB Image Array:\n", image)

# Accessing specific pixels
red_pixel = image[0, 0]
green_pixel = image[0, 1]
blue_pixel = image[0, 2]

print("Red pixel at (0, 0):", red_pixel)
print("Green pixel at (0, 1):", green_pixel)
print("Blue pixel at (0, 2):", blue_pixel)

3x3 RGB Image Array:
 [[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [  0 255 255]
  [255   0 255]]

 [[192 192 192]
  [128 128 128]
  [  0   0   0]]]
Red pixel at (0, 0): [255   0   0]
Green pixel at (0, 1): [  0 255   0]
Blue pixel at (0, 2): [  0   0 255]


#### **➡️ Overview of N-Dimensional Array in Numpy**
- N-Dimensional arrays (also known as **ndarrays**) are a core feature of NumPy.  
- They allow efficient storage and manipulation of multi-dimensional data.  
- These arrays can represent 1D vectors, 2D matrices, or higher-dimensional tensors used in data science, machine learning, and image processing.

---
**➡️ Summary:**
| Function     | Description                          | Example                       | Output Shape |
| ------------ | ------------------------------------ | ----------------------------- | ------------ |
| `np.array()` | Converts lists or tuples into arrays | `np.array([[1,2,3],[4,5,6]])` | (2, 3)       |
| `np.zeros()` | Creates array filled with zeros      | `np.zeros((3,4))`             | (3, 4)       |
| `np.ones()`  | Creates array filled with ones       | `np.ones((2,2,2))`            | (2, 2, 2)    |

**1. From Python Lists or Tuples**: You can create a NumPy array directly from nested Python lists or tuples.

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print(arr)

[[1 2 3]
 [4 5 6]]


**2. Using NumPy Functions**: NumPy provides built-in functions to quickly create arrays of desired shapes and values.

**`a. Using np.zeros():` Creates an array filled with zeros.**

In [4]:
zeros_array = np.zeros((3, 4))  # 3x4 array
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**b. `Using np.ones()`: Creates an array filled with ones.**

In [7]:
ones_array = np.ones((2, 2, 2))  # np.ones((2, 2, 2)) creates 3D array with shape 2×2×2, where all elements are 1.
print(ones_array)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [11]:
import numpy as np

# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array", arr, "\n")

# 2D array
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [11, 12, 13, 14]])
print("2D array", arr, "\n")

# 3x4 array filled with zeros
zeros_array = np.zeros((3, 4))
print("3x4 array filled with zeros", zeros_array, "\n")

# 2x2x2 array filled with ones
ones_array = np.ones((2, 2, 2)) # shape of the array is (2, 2, 2), means there are 2 blocks, each containing a 2x2 matrix.
print("2x2x2 array filled with ones", ones_array)

2D array [[1 2 3]
 [4 5 6]] 

2D array [[ 1  2  3  4]
 [ 4  5  6  7]
 [11 12 13 14]] 

3x4 array filled with zeros [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

2x2x2 array filled with ones [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


#### ➡️ **Overview of functions like **`arange()`** and **`reshape()`****
NumPy provides convenient functions like **`arange()`** and **`reshape()`** to easily create and organize multi-dimensional arrays.

**1. Using `np.arange()`**: The `arange()` function generates a sequence of numbers, similar to Python’s built-in `range()` function, but it returns a **NumPy array** instead of a list.

In [12]:
import numpy as np

arr = np.arange(12)  # Create a 1D array with values from 0 to 11
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


**2. Using `reshape()`:** The `reshape()` function changes the shape of the array into a new dimension — without changing the underlying data.

**➡️ Syntax for 2D array using reshape: `arr.reshape(rows, cols)`**

In [ ]:
import numpy as np

arr = np.arange(12)
arr_2d = arr.reshape(3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


##### **➡️ Syntax for 3D array using reshape: `arr.reshape(depth, rows, cols)`**

In [ ]:
import numpy as np

arr = np.arange(24) # Create a 1D array with values from 0 to 23
arr_3d = arr.reshape(2, 3, 4) # Convert the 1D array into 3D array
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### **Indexing and Slicing in 2D NumPy Arrays**
Indexing in a **2D NumPy** array uses two indices — one for the **row** and one for the **column.**
This allows you to access specific elements, rows, columns, or subarrays efficiently.

---
**➡️ Summary**
| Operation      | Syntax          | Example Output  |
| -------------- | --------------- | --------------- |
| Single Element | `arr[row, col]` | `arr[1, 2] → 6` |
| Entire Row     | `arr[row, :]`   | `[4 5 6]`       |
| Entire Column  | `arr[:, col]`   | `[3 6 9]`       |

**➡️ `Accessing a Single Element`: To access the element at the second row and third column (indices are 0-based):**

In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
element = arr[1, 2]
print(element)   # Output: 6

6


**➡️ `Accessing an Entire Row`: To access all columns from the second row:**

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row = arr[1, :]
print(row)   # Output: [4 5 6]

[4 5 6]


**➡️ Accessing an Entire Column: To access all rows from the third column:**

In [3]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
column = arr[:, 2]
print(column)   # Output: [3 6 9]

[3 6 9]


### **➡️ Slicing Subarrays in 2D NumPy Arrays**
Slicing in **2D arrays** allows you to extract a smaller subarray (a rectangular section) from the original array.
You specify ranges for both rows and columns using the 
- **Syntax: `array[row_start:row_stop, col_start:col_stop]`**
---
➡️ **Tip**
1. The `start index is inclusive`, while the `stop index is exclusive`.
2. You can also use step values, e.g. `arr[::2, ::2]` to skip rows and columns alternately.
---
**➡️ Extracting Specific Regions**
| Description            | Syntax          | Output                      |
| ---------------------- | --------------- | --------------------------- |
| Top-left 2×2 block     | `arr[0:2, 0:2]` | `[[10 20] [50 60]]`         |
| Bottom-right 2×2 block | `arr[2:4, 2:4]` | `[[110 120] [150 160]]`     |
| Middle 2×3 section     | `arr[1:3, 0:3]` | `[[50 60 70] [90 100 110]]` |

**⁉️ Extract a subarray from row indices 1 to 2 and column indices 1 to 3?**

In [7]:
arr = np.arange(24).reshape(6, 4)

subarray = arr[1:3, 1:4]
print(subarray)

[[ 5  6  7]
 [ 9 10 11]]


**➡️ Given a 2-dimensional NumPy array arr of shape (4, 5), perform the following operations:**
- Extract the element at the third row and fourth column.
- Extract the entire first row.
- Extract the entire last column.
- Extract a subarray containing the first three rows and the first two columns.

In [20]:
import numpy as np

arr = np.arange(1, 21).reshape(4, 5)

# Extract the element at 3rd and 4th column
element = arr[2, 3]
print(element)

# Extract the entire first row
row = arr[0, :]
print(row)

# Extract the entire last column
column = arr[:, 4]
print(column)

# Extract a subarray containing the first three rows and the first two columns
row_col = arr[0:3, 0:2]
print(row_col)

14
[1 2 3 4 5]
[ 5 10 15 20]
[[ 1  2]
 [ 6  7]
 [11 12]]


### ➡️ **Indexing and Slicing 3D Arrays in NumPy:**
- Indexing and slicing in **3-dimensional (3D)** arrays extend the concepts from 1D and 2D arrays.
- In a 3D array, you have **three indices** to specify: one for each dimension (**`depth, row, column`**).

##### **Accessing a Single Element: To access the element at position (0, 1, 2)**
**➡️ Explanation:**
- `0` → Selects the first 2D array (depth index).
- `1` → Selects the second row in that 2D array.
- `2` → Selects the third element in that row.

In [15]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)
element = arr[0, 1, 2]

print(element)

6


##### **➡️ Accessing a Whole 2D Array**
**🔹 Explanation:**
- `0` → Selects the first 2D array.
- `:` → Selects all rows in the 2D array.
- `:` → Selects all columns in each row.

In [16]:
arr = np.arange(24).reshape(2, 3, 4)
array_2d = arr[0, :, :]

print(array_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
import numpy as np

arr = np.array([
    [[ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])
element = arr[1, 2, 0] # Extract the element at position (1, 2, 0)
print(element)

array_2d = arr[1, :, 2] # Extract the 3rd column of the second 2D array
print(array_2d)

16
[12 15 18]
