➡️ **Task: Create NumPy Array from Exam Scores**: 

You are a teacher who wants to analyze student exam scores. You have a list of scores and want to convert it into a NumPy array for further analysis.  

🔹 **Instructions:**
- Take a list of exam scores as input.  
- Create a NumPy array from the list.  
- Print the resulting NumPy array.  

**`Input`: 4 3 5 6 7**

In [1]:
import numpy as np

# List of Exam Scores from the user
exam_scores = input("Enter the exam scores seperated by spaces: ").split()
exam_scores = [int(score) for score in exam_scores] # Converting the input string to integers list

# Numpy array from the list of exam scores:
exam_scores_array = np.array(exam_scores)
print(exam_scores_array)

[4 3 5 6 7]


➡️ **Task: `Random Dice Roll Simulator`**: Create a program that simulates rolling a six-sided die multiple times.  

🔹 **Instructions:**
- Take input for the number of times the die should be rolled.  
- Use NumPy's `randint` function to generate random numbers between 1 and 6 (inclusive).  
- Display the results as a NumPy array.  

**Hint:** Use `np.random.randint(1, 7, size=n)` where `n` is the number of rolls.

**`Input`: 3**

In [8]:
import numpy as np

num_rolls = int(input("Enter the number of times to roll the dices: ")) # Ask the user for the number of rolls

# Create a NumPy array of random dice rolls
dice_rolls = np.array([np.random.randint(1, 7) for _ in range(num_rolls)]) # np.random.randint(1, 7, size=num_rolls)
print(dice_rolls)

[3 4 4]


➡️ **Task: `Generate a Sequence of Odd Numbers`**

Create a NumPy array containing a sequence of **odd numbers** from a given start value to an end value.  

🔹 **Instructions:**
- Take input for the **start** and **end** values.  
- Use NumPy’s `arange()` function to generate numbers within the given range.  
- Filter the sequence to include only **odd numbers**.  
- Display the resulting NumPy array.  

**`Input`:  4 & 9**

In [10]:
import numpy as np

start = int(input("Enter the start value: "))
end = int(input("Enter the end value: "))

# Create a NumPy array of odd numbers from start to end
odd_numbers = np.array([num for num in range(start, end + 1) if num % 2 != 0])
print(odd_numbers)

[5 7 9]
