**Compare weather data between two cities**

You are given **temperature data for two cities over a week**. Your task is to **compare the temperatures** by f**inding the difference** between the two cities' temperatures for each day.

**`Input:`**
- **36 28 34 21 25**
- **33 39 34 27 18**

In [1]:
import numpy as np

# Get 7 temperatures for City separated by spaces from input
city_a_temps = list(map(int, input("Enter the Temperarture of City A (space-separated): ").split()))
city_b_temps = list(map(int, input("Enter the Temperarture of City B (space-separated): ").split()))

# Convert lists to NumPy arrays
city_a = np.array(city_a_temps)
city_b = np.array(city_b_temps)

# Calculate the temperature difference
temp_difference = city_a - city_b
print(temp_difference)

[  3 -11   0  -6   7]


➡️ **Calculate Product Sales Across Stores**

You are given **sales data for three products (A, B, and C) in four different stores**. Calculate the **total sales for each product across all stores using matrix multiplication**. 

The **first matrix represents the quantity** of each product sold in each store, and the **second matrix represents the price of each product**.

In [2]:
import numpy as np

# Sales quantity matrix (4 stores x 3 products)
sales_quantity = np.array([
    [10, 5, 3],
    [8, 6, 4],
    [12, 4, 6],
    [6, 8, 2]
])
product_price = np.array([[5], [8], [12]]) # Product price matrix (3 products x 1)

# find total quantity of each product in all four stores
total_quantity_per_product = np.sum(sales_quantity, axis=0)
total_sales = total_quantity_per_product * product_price[:, np.newaxis].T # Calculate total sales

print("Total sales for each product:")
print(total_sales)

Total sales for each product:
[[[180 184 180]]]


➡️ **Symmetric Matrix Checker**

Create a program that **checks if a given square matrix is symmetric**. A symmetric matrix is a **square matrix that is equal to its transpose**. In other words, the element at position (i, j) is equal to the element at position (j, i) for all i and j.

Your task is to implement a function that takes a square matrix as input and r**eturns True if the matrix is symmetric, and False otherwise**. 

**`Input:`**
- **3**
- **2 1 4**
- **1 3 0**
- **4 0 5**

In [3]:
import numpy as np

def is_symmetric(matrix):
    arr = np.array(matrix) # Convert the input list to a NumPy array

    if arr.shape[0] != arr.shape[1]: # Check if the matrix is square
        return False

    return np.array_equal(arr.T, arr) # Implement the symmetry check using matrix transposition

# Get the size of the square matrix from user
n = int(input("Enter the size of the squre matrix: "))
matrix = [list(map(int, input("Enter the Elements (space-separated): ").split())) for _ in range(n)]

# Check if the matrix is symmetric
result = is_symmetric(matrix)
print(result)

True


➡️ **Decode a secret message using matrix inversion**

You are given a **secret message that has been encoded using a 2x2 matrix**. To decode the message, you need to use **matrix inversion**. The **encoding matrix is [[2, 1], [1, 3]]**, and the encoded message is represented as a 2x2 matrix. 

Write a Python program using NumPy to **decode the secret message by inverting the encoding matrix and multiplying it with the encoded message matrix.**

In [4]:
import numpy as np

encoding_matrix = np.array([[2, 1], [1, 3]]) # Encoding matrix
encoded_message = np.array([[5, 4], [7, 9]]) # Encoded message (you can change this to test different messages)

decoded_message = np.linalg.inv(encoding_matrix) * encoded_message # Inverts the matrix and multiplies with the encoded msg

print("Decoded message:")
print(decoded_message)

Decoded message:
[[ 3.  -0.8]
 [-1.4  3.6]]


**Matrix Stability Analyzer**

Create a program that **analyzes the stability of a given square matrix**. A matrix is considered **stable if all its eigenvalues have negative real parts**. The program should take a square matrix as input and determine whether it's stable or not. Additionally, calculate and display the **determinant of the matrix and the eigen values**.

**`Input:`**
- **4**
- **-4   1   2   1**  
- **1  -5   1   2** 
- **2   1  -6   1** 
- **1   2   1  -7**

In [5]:
import numpy as np

def matrix_stability_analyzer(matrix):
    eigenvalues = np.linalg.eigvals(matrix) # Calculate eigenvalues
    is_stable = np.all(np.real(eigenvalues) < 0) # Check stability
    determinant = np.linalg.det(matrix) # Calculate determinant

    return is_stable, determinant, eigenvalues

# Get matrix size from user
n = int(input("Enter the Matrix Size: "))

# Get matrix elements from user
matrix = [list(map(float, input("Enter N Elements for each rows (space-separated): ").split())) for _ in range(n)]

matrix = np.array(matrix) # Convert to numpy array
stability, det, eig = matrix_stability_analyzer(matrix) # Analyze matrix stability

print('stable' if stability else 'unstable')
print(f"Determinant: {det}")
print(f"Eigen Value: {eig}")

stable
Determinant: 395.99999999999966
Eigen Value: [-1.27361128 -5.14228449 -7.29071783 -8.29338641]


➡️ **Check Orthogonal Matrix**

Solve a system of n linear equations using NumPy. The user will input the **coefficient matrix A and the constant vector b**, and the program should **compute and print the solution vector x**.

**`Input:`**
- **3**
- **4 6 5**
- **3 5 7**
- **7 3 2**
- **14 12 15**

In [7]:
import numpy as np

# Get the number of equations from user
n = int(input("Enter the Number of Equations from the User: "))

A = [list(map(float, input("Enter n coefficients for each equation (space-separated): ").split())) for _ in range(n)]
A = np.array(A)

# Enter n constants for each equation
b = list(map(float, input("Enter n constants for each equation: ").split()))
b = np.array(b)

x = np.linalg.solve(A,b)
print(x)

[1.63095238 0.98809524 0.30952381]
