➡️ **Task: Generate 3D Array of Ones with Custom Dimensions**

Write a function that takes three integers as input — **depth**, **rows**, and **columns** — and returns a **3D NumPy array** filled with ones, having the specified dimensions.

**`Input`: 2 1 3**

In [1]:
import numpy as np

def create_3d_ones(depth, rows, columns):
    array = np.ones((depth, rows, columns), dtype=int)

    return array

# Take depth, rows, and columns as input
depth, rows, cols = map(int, input().split())
result = create_3d_ones(depth, rows, cols)

print(result)

[[[1 1 1]]

 [[1 1 1]]]


➡️ **Task: Reshape Array to User-Specified 3D Dimensions**

Write a program that:

1. Takes user input for the **dimensions** of a 3D array: **depth**, **rows**, and **columns**.
2. Takes a list of integers as input.
3. Creates a **1D NumPy array** from the input list.
4. Reshapes the 1D array into a **3D array** using the specified dimensions.

**`Input:`**
- **3**
- **2**
- **3**
- **9 11 17 5 6 14 8 21 9 5 16 18 26 3 45 28 7 13**

In [8]:
import numpy as np

depth = int(input("Enter depth: "))
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of cols: "))

elements = list(map(int, input("Enter elements separated by spaces: ").split()))

if len(elements) != depth * rows * cols:
    print(f"Error: You must enter exactly {depth*rows*cols} elements")
else:
    array_1d = np.array(elements)
    reshaped_array = np.reshape(array_1d, (depth, rows, cols))
    print(reshaped_array)

[[[ 9 11 17]
  [ 5  6 14]]

 [[ 8 21  9]
  [ 5 16 18]]

 [[26  3 45]
  [28  7 13]]]


➡️ **Task: Chessboard Square Extractor**

Write a program that:

1. Simulates an **8x8 chessboard** using a 2D NumPy array:
   - `0` represents **white squares**.
   - `1` represents **black squares**.
2. Takes user inputs `a` and `b` representing the **row** and **column** of a square on the chessboard.
3. Extracts a **3x3 subgrid** centered on the selected square `(a, b)`.
4. Displays the resulting 3x3 subgrid.

**`Input:`**
- **4**
- **5**

In [17]:
import numpy as np

# Create the chessboard
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, 0::2] = 1
chessboard[0::2, 1::2] = 1

a = int(input("Enter row number (0 - 7): ")) # Take row number(0-7) as input
b = int(input("Enter column number (0 - 7): ")) # Take column number(0-7) as input

# Extract the 3x3 subgrid
extracted_array = chessboard[max(0, a-1):min(8, a+2), max(0, b-1):min(8, b+2)]
print(extracted_array)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


➡️ **Extract a cube from within a 3D array**

Given a 3D NumPy array of shape (5, 5, 5) filled with random integers from 0 to 99. 

Extract a cube of size (a, b, c) starting from the position (1, 1, 1) within the array, where a, b, and c are user inputs. Display the extracted cube.

**`Input:`**
- **3**
- **2**
- **4**

In [25]:
import numpy as np

# Create a 5x5x5 3D array with random integers from 0 to 99
array_3d = np.random.randint(0, 100, size=(5, 5, 5))

# Get user input for cube dimensions
a = int(input("Enter depth to extract: "))
b = int(input("Enter number of rows to extract: "))
c = int(input("Enter number of columns to extract: "))

# Extract the cube from the 3D array
array_3d = array_3d[1:a+1, 1:b+1, 1:c+1]

# Print the extracted cube
print(array_3d)

[[[80  9 51 48]
  [16 32 67 37]]

 [[45 94 84  6]
  [23 54 64 85]]

 [[ 1 25 93 90]
  [15 82 92 88]]]


➡️ **Extract specific rows from all layers of 3D array**

In this task, you will create a 3D NumPy array and **extract specific rows from all layers of the array**. You'll be given the dimensions of the array and the row numbers to extract. 

Your goal is to **create the array**, **fill it with sequential numbers**, and then **extract the specified rows** from each layer.

**`Input:`**
- **3**
- **3**
- **2**
- **1 2**

In [33]:
import numpy as np

def extract_rows_from_layers(depth, rows, cols, row_indices):
    array_3d = np.arange(depth * rows * cols).reshape(depth, rows, cols) # Create a 3D array with the given dimensions

    result = array_3d[:, row_indices, :] # Extract the specified rows from all layers
    return result

depth = int(input("Enter depth: ")) # Take depth of the 3D array as input
rows = int(input("Enter number of rows: ")) # Take number of rows as input
cols = int(input("Enter number of columns: ")) # Take number of columns as input

# Take row_indices to extract as input
row_indices = list(map(int, input("Enter row indices to extract in each layer (space separated): ").split()))

# Call the function and print the result
result = extract_rows_from_layers(depth, rows, cols, row_indices)
print(result)

[[[ 2  3]
  [ 4  5]]

 [[ 8  9]
  [10 11]]

 [[14 15]
  [16 17]]]
