➡️ **Merge Student Scores from Two Classes**

You are a teacher who has just finished grading two classes. You want to **combine the scores of both classes into a single array** for further analysis.  

**`Input:`**
- **20, 35, 18, 44**
- **23, 36, 37, 24**

In [1]:
import numpy as np

# Get scores(comma-separated) from user
class_a_array = np.array(list(map(int, input("Enter the Scores of Students in Class A: ").split(','))))
class_b_array = np.array(list(map(int, input("Enter the Scores of Students in Class B: ").split(','))))

combined_scores = np.concatenate((class_a_array, class_b_array)) # Concatenate the two arrays

print(
    f"Combined Scores: {combined_scores}\n"
    f"Total Number of Scores: {len(combined_scores)}\n"
    f"Average Scores: {np.mean(combined_scores)}"
)

Combined Scores: [20 35 18 44 23 36 37 24]
Total Number of Scores: 8
Average Scores: 29.625


➡️ **Create a Repeating DNA Sequence** 

In this task, you will create a **repeating DNA sequence** using NumPy arrays. You’ll be given two arrays representing **DNA base pairs**, and you need to **repeat them a specified number of times** to form a longer DNA chain.  

🔹 **Task:**
- Take two arrays of DNA base pairs as input.  
- Use `np.tile()` to repeat the sequences a specified number of times.  
- Combine both repeated arrays using `np.concatenate()` to form the full DNA sequence.  

**`Input`: 3**

In [2]:
import numpy as np

# DNA base pairs
pair1 = np.array(['A', 'T'])
pair2 = np.array(['C', 'G'])

n = int(input("Enter the Number of Repetitions: ")) # Get the number of repetitions

# Create the repeated DNA sequence
array_concat = np.concatenate([pair1, pair2])
dna_sequence = np.tile(array_concat, n)

print(dna_sequence)

['A' 'T' 'C' 'G' 'A' 'T' 'C' 'G' 'A' 'T' 'C' 'G']


➡️ **Convert country names to uppercase**

In this practice problem, you will create a NumPy array containing country names and convert them to uppercase using NumPy's string functions. 

**`Input`: India,Brazil,Canada,Japan,Australia**

In [3]:
import numpy as np

# Input comma-separated country names from the user
country_array = np.array(input("Enter the Country Name (comma-separated): ").split(','))
uppercase_countries = np.char.upper(country_array) # Convert country names to uppercase

print(uppercase_countries)

['INDIA' 'BRAZIL' 'CANADA' 'JAPAN' 'AUSTRALIA']


➡️ **Title Case Converter for Movie Titles**

You are given an array of **movie titles in lowercase**. Your task is to create a NumPy program that converts these titles into **title case**,  
while keeping small words in lowercase **unless they are the first or last word** in the title.

In [4]:
import numpy as np

def title_case_movies(movies):
    # List of words that should not be capitalized unless they're the first word
    small_words = np.array(['a', 'an', 'the', 'and', 'but', 'or', 'for', 'nor', 'on', 'at', 'to', 'from', 'by', 'in', 'of'])

    words = np.char.split(movies) # Split each movie title into words

    for index, title in enumerate(words): # Unpacks & separates the index, title from the words
        for index, movie_word in enumerate(title): # Unpacks & separates the index, movie_word from the title
            if movie_word not in small_words or index == 0: # Checks whether index == 0 or movie_word in small_words
                title[index] = movie_word.title() # Converts the words into title case

    return np.array([' '.join(title) for title in words]) # Join the words back into movie titles

movies = np.array(['the godfather', 'pulp fiction', 'house of the dragon', 'the dark knight', 'forrest gump', 'the matrix', 'taare zameen par'])
result = title_case_movies(movies)
print(result)

['The Godfather' 'Pulp Fiction' 'House of the Dragon' 'The Dark Knight'
 'Forrest Gump' 'The Matrix' 'Taare Zameen Par']


➡️ **Parse CSV - Split CSV data into a NumPy array**

Create a function that takes a **string containing comma-separated values (CSV)** and **converts it into a 2D NumPy array**. 
The function should **split the input string by commas and newlines**, then **create a NumPy array** from the resulting data. Each row in the CSV should become a row in the NumPy array.

In [36]:
import numpy as np

def parse_csv(csv_string):
    rows = csv_string.split('\n') # Split the csv_string into rows
    row_array = np.char.split(rows, ',')     # Split each row into values

    # Convert the list of lists to a NumPy array
    result_array = np.array([result for result in row_array], dtype=int)

    return result_array

csv_data = """1,2,3
4,5,6
7,8,9"""

result = parse_csv(csv_data)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


➡️ **Join Student Names for Attendance**

Create a NumPy array of student names and j**oin them into a single string** for attendance purposes. Use a **comma and space (', ') as the separator** between names.

In [42]:
import numpy as np

# Create a NumPy array of student names
students = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])

# Join the names using a comma and space as separator
attendance_list = ', '.join(students)
print("Attendance list:", attendance_list)


Attendance list: Alice, Bob, Charlie, David, Eve


➡️ **Find occurrences of a substring in a NumPy array**

Create a NumPy program that **searches for a given substring** within an array of strings. The program should **display the indices of the array elements** that contain the substring. Use NumPy's string functions to perform the search.

**`Input`: is**

In [62]:
import numpy as np

# Create a NumPy array of strings
texts = np.array(['Hello, world!', 'Python is awesome', 'NumPy makes it easy', 'Search me', 'Python makes coding fun',
                  'Coding is creative'])

search_string = input("Enter the substring to search: ")

# Find the indices of elements containing the substring
result = np.char.find(texts, search_string)
indices = np.where(result != -1)[0]

print(indices)

[1 4]


➡️ **Replace vowels in a NumPy array of strings**

Create a NumPy program that takes a list of words as input, **converts it into a NumPy array**, and then **replaces all vowels (a, e, i, o, u)** in each word **with an asterisk (*)**. The program should then display the modified array.

**`Input`: programming codechef python contests**

In [65]:
import numpy as np

words = input("Enter the Sentence: ").split() # Get input words from the user
word_array = np.array(words) # Convert the list to a NumPy array

# Replace vowels with asterisks
for vowels in 'aeiouAEIOU':
    word_array = np.char.replace(word_array, vowels, '*')

print(word_array)

['pr*gr*mm*ng' 'c*d*ch*f' 'pyth*n' 'c*nt*sts']


➡️ **Remove spaces from scientist names**

You are given a NumPy array containing **names of famous scientists with extra spaces**. Your goal is to **remove all the blank characters (spaces) from each name** in the array using NumPy's string functions.

In [74]:
import numpy as np

# Input: Array of scientist names with extra spaces
scientists = np.array([" Albert  Einstein ", "Isaac  Newton", " Marie  Curie ", "Charles  Darwin"])

# Your code here to remove spaces from each name
cleaned_names = np.char.strip(np.char.replace(scientists, " ", ''))
print(cleaned_names)

['AlbertEinstein' 'IsaacNewton' 'MarieCurie' 'CharlesDarwin']


➡️ **Character Type Counter**

Create a NumPy program that **takes a string input and counts the number of alphabetic and numeric characters** in it. Use NumPy's character checking **functions isalpha() and isnumeric()** to determine the character types.

**`Input`: ahd3d92hd932h29dh2dh**

In [78]:
import numpy as np

def count_char_types(input_string):
    # Create an array of single characters
    char_array = np.array(list(input_string))

    # Count alphabetic and numeric characters using NumPy string functions
    alpha_count = np.sum(np.char.isalpha(char_array))
    num_count = np.sum(np.char.isdigit(char_array))

    return alpha_count, num_count

# Get input string from user
user_input = input()

# Call the function and print results
alpha, num = count_char_types(user_input)

# Print alphabetic characters
print(alpha)

# Print numeric characters
print(num)


11
9
